### ISSUE TITLE
Android TV support?

### ISSUE THREAD

**Issue by emouawad** [mocklets/pluto#106]
Does this lib support Android TV?

Tested the lib on simulator for apis 28 30 and 31, I see from the logs that activity_tracker is working fine and traking the lifecycles fine.
ANR and logging events are also working fine.
Toast message also shows saying that pluto has been initialized successfully.

But for some reason, no Pluto notification has been generated, so I am unable to launch the underlying Pluto views.

Also, Is there any other way that Pluto can be launched (as an alternative) other than from the notification?

**Comment by srtvprateek** [comment]
hey @emouawad ,
we support a floating notch to open the Pluto UI, not sure what's blocking notification on Android TV, will look into this.
Also, we are working on the new version of Pluto, where you can trigger the Pluto UI manually also.
will keep you posted.

**Comment by emouawad** [comment]
Thanks for your reply,
Yes manually launching the UI should do it, I think
Would be happy to test the new version when it comes, Thanks

**Comment by srtvprateek** [comment]
thanks to @tpakis, this is resolved
will be published in version `1.1.3`

**Comment by codershailu** [comment]
The functionality doesn't seem to be functioning properly on Android TV. I need to develop a new Fragment to display various options for viewing network logs and crashes. Additionally, when using Android TV, interactions are typically based on remote control input rather than touch, and the current setup lacks support for navigation via focus. Integrating support for focus-based navigation can enhance the user experience on Android TV devices.
