### ISSUE TITLE
Task :app:mergeDebugResources FAILED

### ISSUE THREAD

**Issue by Dalakoti07** [mocklets/pluto#23]
**Describe the bug**
Build getting failed with Task :app:mergeDebugResources FAILED error

**To Reproduce**
1. follow the startup guide
2. Add dependency
3. Build project
4. See build error

**Screenshots**
https://imgur.com/a/iMkysPE

**Full error logs**
`> Task :app:mergeDebugResources
/home/dalakoti07/.gradle/caches/transforms-3/ac13ed731ff91608bb885e6070e58d98/transformed/preference-1.1.1/res/values/values.xml:424:4: Duplicate value for resource 'attr/min' with config 'DEFAULT' and product ''. Resource was previously defined here: /home/dalakoti07/AndroidStudioProjects/consumer/commons/ui/build/intermediates/packaged_res/debug/values/values.xml:1749:4: .

> Task :app:mergeDebugResources FAILED
Execution failed for task ':app:mergeDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed. Check logs for details.

`

**Comment by srtvprateek** [comment]
@Dalakoti07 can you share the library version.

**Comment by Dalakoti07** [comment]
version 1.0.4

Gradle: 7.0.0
kotlin_version = '1.5.21'

**Comment by srtvprateek** [comment]
@Dalakoti07 we figured out the root cause of the issue.
in one of the dependencies `'androidx.preference:preference-ktx:1.1.1'`, 
a property `SeekBarPreference` is defined with attr `min`, which is conflicting with your value.

trying to figure out a workaround it, but as a general practice, you can rename the attr key to something with does not conflict with any of the dependencies.

**Comment by Dalakoti07** [comment]
Thanks @srtvprateek looking forward for the fix

**Comment by Dalakoti07** [comment]
As of now I have changed my attribute values and its working fine. Not getting any conflicting build issue
