### ISSUE TITLE
Does pluto able to intercept HTTP Request e.g other than Okhttp?

### ISSUE THREAD

**Issue by mochadwi** [mocklets/pluto#8]
e.g: HttpConnection, FastNetworking, Ktor, etc

**Comment by mocklets-tech** [comment]
hey @mochadwi,
for now, Pluto intercepts only Okhttp requests.

if you have any specific usecase, do share with us, we will try to include it in our future releases.

**Comment by amankgo** [comment]
We can add an optional support for logging `HttpURLConnection` through `URLStreamHandlerFactory`, `URLStreamHandler`, `URL.setURLStreamHandlerFactory()`

Maybe some level of logging can be achieved through this.

See this answer: https://stackoverflow.com/a/26409796/2960297

**Comment by mlilienberg** [comment]
The PlutoInterceptor works great but additionally it would be nice to have access to NetworkCallsRepo, so that anyone can write a custom interceptor for any http client. We would like to use this to write our own interceptors for gPRC clients based on io.grpc.ManagedChannel. In my opinion this should not be difficult to achieve, only ResponseData.Protocol needs to be changed to not depend on okhttp3.protocol.

**Comment by srtvprateek** [comment]
@mlilienberg nice feature suggestion.
will look into this
